import {
  Direction,
  LevelThemes,
  PLACEMENT_TYPE_FIRE,
  PLACEMENT_TYPE_FIRE_PICKUP,
  PLACEMENT_TYPE_FLOUR,
  PLACEMENT_TYPE_FLYING_ENEMY,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_GROUND_ENEMY,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_ICE,
  PLACEMENT_TYPE_ICE_PICKUP,
  PLACEMENT_TYPE_INFECTED_HERO,
  PLACEMENT_TYPE_KEY,
  PLACEMENT_TYPE_LOCK,
  PLACEMENT_TYPE_ROAMING_ENEMY,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_TELEPORT,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_WATER_PICKUP,
} from "~/constants/helpers";

const level1 = {
  theme: LevelThemes.Blue,
  tilesWidth: 12,
  tilesHeight: 6,
  placements: [
    { x: 1, y: 1, type: PLACEMENT_TYPE_HERO },
    { x: 2, y: 2, type: PLACEMENT_TYPE_KEY, color: "GREEN" },
    { x: 4, y: 1, type: PLACEMENT_TYPE_LOCK, color: "GREEN" },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 4,
      y: 4,
    },

    {
      type: PLACEMENT_TYPE_WALL,
      x: 4,
      y: 2,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 4,
      y: 3,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 4,
      y: 5,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 4,
      y: 6,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 6,
      y: 1,
    },
    {
      type: PLACEMENT_TYPE_LOCK,
      x: 6,
      y: 2,
      color: "GREEN",
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 7,
      y: 1,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 6,
      y: 4,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 6,
      y: 4,
    },
    {
      type: PLACEMENT_TYPE_LOCK,
      x: 6,
      y: 5,
      color: "BLUE",
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 6,
      y: 6,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 7,
      y: 6,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 7,
      y: 4,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 8,
      y: 4,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 9,
      y: 4,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 9,
      y: 4,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 9,
      y: 2,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 9,
      y: 3,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 9,
      y: 1,
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 9,
      y: 5,
    },
    {
      type: PLACEMENT_TYPE_LOCK,
      x: 9,
      y: 6,
      color: "GREEN",
    },
    {
      type: PLACEMENT_TYPE_WALL,
      x: 6,
      y: 3,
    },
    { x: 8, y: 1, type: PLACEMENT_TYPE_FLOUR },
    { x: 8, y: 2, type: PLACEMENT_TYPE_INFECTED_HERO },
    { x: 5, y: 6, type: PLACEMENT_TYPE_FLOUR },
    { x: 8, y: 3, type: PLACEMENT_TYPE_KEY, color: "BLUE" },
    { x: 11, y: 2, type: PLACEMENT_TYPE_GOAL },

    // { x: 4, y: 2, type: PLACEMENT_TYPE_WALL },
    // { x: 4, y: 3, type: PLACEMENT_TYPE_WALL },
    // { x: 4, y: 4, type: PLACEMENT_TYPE_WALL },
    // { x: 4, y: 5, type: PLACEMENT_TYPE_WALL },
    // { x: 4, y: 6, type: PLACEMENT_TYPE_WALL },
    // { x: 6, y: 2, type: PLACEMENT_TYPE_WALL },
    // { x: 7, y: 2, type: PLACEMENT_TYPE_WALL },
    // { x: 8, y: 2, type: PLACEMENT_TYPE_WALL },
    // { x: 9, y: 2, type: PLACEMENT_TYPE_WALL },
    // { x: 10, y: 2, type: PLACEMENT_TYPE_WALL },

    // { x: 8, y: 2, type: PLACEMENT_TYPE_INFECTED_HERO },

    // { x: 7, y: 4, type: PLACEMENT_TYPE_WALL },

    // { x: 3, y: 1, type: PLACEMENT_TYPE_THIEF },

    // { x: 3, y: 2, type: PLACEMENT_TYPE_TELEPORT },
    // { x: 7, y: 6, type: PLACEMENT_TYPE_TELEPORT },

    // { x: 7, y: 1, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: false },
    // { x: 4, y: 2, type: PLACEMENT_TYPE_SWITCH_DOOR, isRaised: true },
    // { x: 4, y: 1, type: PLACEMENT_TYPE_SWITCH },

    // { x: 3, y: 3, type: PLACEMENT_TYPE_FIRE },
    // { x: 4, y: 3, type: PLACEMENT_TYPE_FIRE },
    // { x: 5, y: 3, type: PLACEMENT_TYPE_FIRE },

    // { x: 3, y: 4, type: PLACEMENT_TYPE_ICE, corner: "TOP_LEFT" },
    // { x: 3, y: 6, type: PLACEMENT_TYPE_ICE, corner: "BOTTOM_LEFT" },
    // { x: 5, y: 4, type: PLACEMENT_TYPE_ICE, corner: "TOP_RIGHT" },
    // { x: 5, y: 6, type: PLACEMENT_TYPE_ICE, corner: "BOTTOM_RIGHT" },
    // { x: 3, y: 5, type: PLACEMENT_TYPE_ICE },
    // { x: 4, y: 5, type: PLACEMENT_TYPE_ICE },
    // { x: 5, y: 5, type: PLACEMENT_TYPE_ICE },
    // { x: 4, y: 4, type: PLACEMENT_TYPE_ICE },
    // { x: 4, y: 6, type: PLACEMENT_TYPE_ICE },

    // { x: 5, y: 5, type: PLACEMENT_TYPE_ICE },
    // { x: 3, y: 8, type: PLACEMENT_TYPE_WALL },
    // { x: 6, y: 7, type: PLACEMENT_TYPE_WATER_PICKUP },
    // { x: 6, y: 8, type: PLACEMENT_TYPE_ICE_PICKUP },
    // { x: 6, y: 9, type: PLACEMENT_TYPE_FIRE_PICKUP },

    // { x: 7, y: 7, type: PLACEMENT_TYPE_WATER },
    // { x: 8, y: 7, type: PLACEMENT_TYPE_WATER },
    // { x: 7, y: 8, type: PLACEMENT_TYPE_WATER },
    // { x: 8, y: 8, type: PLACEMENT_TYPE_WATER },
    // { x: 5, y: 8, type: PLACEMENT_TYPE_GROUND_ENEMY },
    // { x: 3, y: 5, type: PLACEMENT_TYPE_ROAMING_ENEMY },
    // { x: 8, y: 1, type: PLACEMENT_TYPE_KEY, color: "BLUE" },
    // { x: 5, y: 8, type: PLACEMENT_TYPE_LOCK, color: "BLUE" },
    // {
    //   x: 2,
    //   y: 1,
    //   type: PLACEMENT_TYPE_FLYING_ENEMY,
    // },
    // { x: 5, y: 5, type: PLACEMENT_TYPE_FLOUR },
    // { x: 4, y: 5, type: PLACEMENT_TYPE_FLOUR },
    // { x: 3, y: 7, type: PLACEMENT_TYPE_FLOUR },
  ],
};

export default level1;
