import {
  Direction,
  LevelThemes,
  PLACEMENT_TYPE_CONVEYOR,
  PLACEMENT_TYPE_FIRE,
  PLACEMENT_TYPE_FIRE_PICKUP,
  PLACEMENT_TYPE_FLOUR,
  PLACEMENT_TYPE_FLYING_ENEMY,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_GROUND_ENEMY,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_ICE,
  PLACEMENT_TYPE_ICE_PICKUP,
  PLACEMENT_TYPE_INFECTED_HERO,
  PLACEMENT_TYPE_KEY,
  PLACEMENT_TYPE_LOCK,
  PLACEMENT_TYPE_ROAMING_ENEMY,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_WATER_PICKUP,
} from "~/constants/helpers";

const level8 = {
  theme: LevelThemes.Pink,
  tilesWidth: 11,
  tilesHeight: 11,
  placements: [
    { type: PLACEMENT_TYPE_HERO, x: 2, y: 2 },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 4, y: 2, direction: Direction.Right },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 5, y: 2, direction: Direction.Right },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 6, y: 2, direction: Direction.Right },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 7, y: 2, direction: Direction.Right },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 8, y: 2, direction: Direction.Right },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 9, y: 2, direction: Direction.Bottom },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 10, y: 4, direction: Direction.Bottom },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 10, y: 5, direction: Direction.Bottom },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 10, y: 6, direction: Direction.Bottom },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 10, y: 7, direction: Direction.Bottom },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 10, y: 8, direction: Direction.Bottom },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 10, y: 9, direction: Direction.Left },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 8, y: 10, direction: Direction.Left },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 7, y: 10, direction: Direction.Left },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 6, y: 10, direction: Direction.Left },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 5, y: 10, direction: Direction.Left },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 4, y: 10, direction: Direction.Left },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 3, y: 10, direction: Direction.Top },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 2, y: 8, direction: Direction.Top },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 2, y: 7, direction: Direction.Top },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 2, y: 6, direction: Direction.Top },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 2, y: 5, direction: Direction.Top },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 2, y: 4, direction: Direction.Top },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 2, y: 3, direction: Direction.Right },
    { type: PLACEMENT_TYPE_ICE, x: 3, y: 3 },
    { type: PLACEMENT_TYPE_ICE, x: 3, y: 4 },
    { type: PLACEMENT_TYPE_ICE, x: 3, y: 5 },
    { type: PLACEMENT_TYPE_ICE, x: 3, y: 7 },
    { type: PLACEMENT_TYPE_ICE, x: 3, y: 8 },
    { type: PLACEMENT_TYPE_ICE, x: 3, y: 9 },
    { type: PLACEMENT_TYPE_ICE, x: 4, y: 9 },
    { type: PLACEMENT_TYPE_ICE, x: 5, y: 9 },
    { type: PLACEMENT_TYPE_ICE, x: 7, y: 9 },
    { type: PLACEMENT_TYPE_ICE, x: 8, y: 9 },
    { type: PLACEMENT_TYPE_ICE, x: 9, y: 9 },
    { type: PLACEMENT_TYPE_ICE, x: 9, y: 8 },
    { type: PLACEMENT_TYPE_ICE, x: 9, y: 7 },
    { type: PLACEMENT_TYPE_ICE, x: 9, y: 6 },
    { type: PLACEMENT_TYPE_ICE, x: 9, y: 5 },
    { type: PLACEMENT_TYPE_ICE, x: 9, y: 4 },
    { type: PLACEMENT_TYPE_ICE, x: 9, y: 3 },
    { type: PLACEMENT_TYPE_ICE, x: 4, y: 3 },
    { type: PLACEMENT_TYPE_ICE, x: 5, y: 3 },
    { type: PLACEMENT_TYPE_ICE, x: 6, y: 3 },
    { type: PLACEMENT_TYPE_ICE, x: 7, y: 3 },
    { type: PLACEMENT_TYPE_ICE, x: 8, y: 3 },
    { type: PLACEMENT_TYPE_WATER, x: 4, y: 4 },
    { type: PLACEMENT_TYPE_WATER, x: 5, y: 4 },
    { type: PLACEMENT_TYPE_WATER, x: 6, y: 4 },
    { type: PLACEMENT_TYPE_WATER, x: 7, y: 4 },
    { type: PLACEMENT_TYPE_WATER, x: 8, y: 4 },
    { type: PLACEMENT_TYPE_WATER, x: 8, y: 5 },
    { type: PLACEMENT_TYPE_WATER, x: 8, y: 6 },
    { type: PLACEMENT_TYPE_WATER, x: 7, y: 8 },
    { type: PLACEMENT_TYPE_WATER, x: 8, y: 8 },
    { type: PLACEMENT_TYPE_WATER, x: 8, y: 7 },
    { type: PLACEMENT_TYPE_WATER, x: 5, y: 8 },
    { type: PLACEMENT_TYPE_WATER, x: 4, y: 8 },
    { type: PLACEMENT_TYPE_WATER, x: 4, y: 7 },
    { type: PLACEMENT_TYPE_WATER, x: 4, y: 6 },
    { type: PLACEMENT_TYPE_WATER, x: 4, y: 5 },
    { type: PLACEMENT_TYPE_FIRE, x: 5, y: 5 },
    { type: PLACEMENT_TYPE_FIRE, x: 7, y: 5 },
    { type: PLACEMENT_TYPE_FIRE, x: 7, y: 6 },
    { type: PLACEMENT_TYPE_FIRE, x: 7, y: 7 },
    { type: PLACEMENT_TYPE_FIRE, x: 6, y: 7 },
    { type: PLACEMENT_TYPE_FIRE, x: 5, y: 7 },
    { type: PLACEMENT_TYPE_FIRE, x: 5, y: 6 },
    { type: PLACEMENT_TYPE_GOAL, x: 6, y: 6 },
    { type: PLACEMENT_TYPE_FLOUR, x: 4, y: 1 },
    { type: PLACEMENT_TYPE_FLOUR, x: 8, y: 1 },
    { type: PLACEMENT_TYPE_FLOUR, x: 11, y: 4 },
    { type: PLACEMENT_TYPE_FLOUR, x: 1, y: 4 },
    { type: PLACEMENT_TYPE_FLOUR, x: 1, y: 8 },
    { type: PLACEMENT_TYPE_WALL, x: 6, y: 1 },
    { type: PLACEMENT_TYPE_THIEF, x: 2, y: 9 },
    { type: PLACEMENT_TYPE_THIEF, x: 3, y: 2 },
    { type: PLACEMENT_TYPE_THIEF, x: 10, y: 3 },
    { type: PLACEMENT_TYPE_THIEF, x: 9, y: 10 },
    { type: PLACEMENT_TYPE_FIRE, x: 6, y: 5 },
    { type: PLACEMENT_TYPE_FLOUR, x: 4, y: 11 },
    { type: PLACEMENT_TYPE_FLOUR, x: 8, y: 11 },
    { type: PLACEMENT_TYPE_LOCK, x: 6, y: 11 },
    { type: PLACEMENT_TYPE_LOCK, x: 11, y: 6, color: "GREEN" },
    { type: PLACEMENT_TYPE_SWITCH_DOOR, x: 1, y: 6 },
    { type: PLACEMENT_TYPE_SWITCH, x: 3, y: 6 },
    { type: PLACEMENT_TYPE_KEY, x: 2, y: 10 },
    { type: PLACEMENT_TYPE_KEY, x: 10, y: 10, color: "GREEN" },
    { type: PLACEMENT_TYPE_ICE_PICKUP, x: 10, y: 2 },
    { type: PLACEMENT_TYPE_WATER, x: 6, y: 8 },
    { type: PLACEMENT_TYPE_ICE, x: 6, y: 9 },

    { type: PLACEMENT_TYPE_FIRE_PICKUP, x: 6, y: 8 },
    { type: PLACEMENT_TYPE_WATER_PICKUP, x: 6, y: 9 },
    {
      type: PLACEMENT_TYPE_GROUND_ENEMY,
      x: 11,
      y: 11,
      initialDirection: Direction.Top,
    },
    {
      type: PLACEMENT_TYPE_GROUND_ENEMY,
      x: 1,
      y: 1,
      initialDirection: Direction.Bottom,
    },
  ],
};

export default level8;
