import {
  Direction,
  LevelThemes,
  PLACEMENT_TYPE_CONVEYOR,
  PLACEMENT_TYPE_FLOUR,
  PLACEMENT_TYPE_FLYING_ENEMY,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_GROUND_ENEMY,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_INFECTED_HERO,
  PLACEMENT_TYPE_ROAMING_ENEMY,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_WATER_PICKUP,
} from "~/constants/helpers";

const level5 = {
  theme: LevelThemes.Green,
  tilesWidth: 9,
  tilesHeight: 9,
  placements: [
    { type: PLACEMENT_TYPE_HERO, x: 2, y: 5 },
    { type: PLACEMENT_TYPE_WALL, x: 3, y: 1 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 1 },
    { type: PLACEMENT_TYPE_WALL, x: 5, y: 1 },
    { type: PLACEMENT_TYPE_WALL, x: 6, y: 1 },
    { type: PLACEMENT_TYPE_WALL, x: 7, y: 1 },
    { type: PLACEMENT_TYPE_WALL, x: 8, y: 1 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 5 },
    { type: PLACEMENT_TYPE_WALL, x: 7, y: 5 },
    { type: PLACEMENT_TYPE_WALL, x: 2, y: 9 },
    { type: PLACEMENT_TYPE_WALL, x: 3, y: 9 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 9 },
    { type: PLACEMENT_TYPE_WALL, x: 5, y: 9 },
    { type: PLACEMENT_TYPE_WALL, x: 6, y: 9 },
    { type: PLACEMENT_TYPE_WALL, x: 7, y: 9 },
    { type: PLACEMENT_TYPE_WALL, x: 8, y: 9 },
    { type: PLACEMENT_TYPE_WALL, x: 2, y: 1 },
    { type: PLACEMENT_TYPE_WALL, x: 3, y: 5 },
    { type: PLACEMENT_TYPE_WALL, x: 6, y: 5 },
    { type: PLACEMENT_TYPE_GROUND_ENEMY, x: 9, y: 2 },
    { type: PLACEMENT_TYPE_GROUND_ENEMY, x: 9, y: 3 },
    { type: PLACEMENT_TYPE_GROUND_ENEMY, x: 9, y: 4 },
    { type: PLACEMENT_TYPE_GROUND_ENEMY, x: 9, y: 6 },
    { type: PLACEMENT_TYPE_GROUND_ENEMY, x: 9, y: 7 },
    { type: PLACEMENT_TYPE_GROUND_ENEMY, x: 9, y: 8 },
    {
      type: PLACEMENT_TYPE_GROUND_ENEMY,
      x: 1,
      y: 8,
      initialDirection: Direction.Bottom,
    },
    {
      type: PLACEMENT_TYPE_GROUND_ENEMY,
      x: 9,
      y: 1,
      initialDirection: Direction.Top,
    },
    { type: PLACEMENT_TYPE_FLOUR, x: 7, y: 3 },
    { type: PLACEMENT_TYPE_FLOUR, x: 7, y: 7 },
    { type: PLACEMENT_TYPE_FLOUR, x: 3, y: 7 },
    { type: PLACEMENT_TYPE_FLOUR, x: 3, y: 3 },
    { type: PLACEMENT_TYPE_FLOUR, x: 5, y: 5 },
    { type: PLACEMENT_TYPE_GOAL, x: 8, y: 5 },
  ],
};

export default level5;
