import {
  Direction,
  LevelThemes,
  PLACEMENT_TYPE_FLOUR,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_KEY,
  PLACEMENT_TYPE_LOCK,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_CONVEYOR,
  PLACEMENT_TYPE_INFECTED_HERO,
} from "~/constants/helpers";

const level3 = {
  theme: LevelThemes.Blue,
  tilesWidth: 11,
  tilesHeight: 11,
  placements: [
    { type: PLACEMENT_TYPE_HERO, x: 2, y: 2 },
    { type: PLACEMENT_TYPE_WALL, x: 1, y: 4 },
    { type: PLACEMENT_TYPE_WALL, x: 3, y: 4 },
    { type: PLACEMENT_TYPE_WALL, x: 5, y: 4 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 1 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 5 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 4 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 3 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 7 },
    { type: PLACEMENT_TYPE_WALL, x: 5, y: 8 },
    { type: PLACEMENT_TYPE_WALL, x: 3, y: 8 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 8 },
    { type: PLACEMENT_TYPE_WALL, x: 1, y: 8 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 11 },
    { type: PLACEMENT_TYPE_WALL, x: 7, y: 8 },
    { type: PLACEMENT_TYPE_WALL, x: 8, y: 8 },
    { type: PLACEMENT_TYPE_WALL, x: 9, y: 8 },
    { type: PLACEMENT_TYPE_WALL, x: 8, y: 9 },
    { type: PLACEMENT_TYPE_WALL, x: 8, y: 7 },
    { type: PLACEMENT_TYPE_WALL, x: 8, y: 11 },
    { type: PLACEMENT_TYPE_WALL, x: 11, y: 8 },
    { type: PLACEMENT_TYPE_WALL, x: 7, y: 4 },
    { type: PLACEMENT_TYPE_WALL, x: 9, y: 4 },
    { type: PLACEMENT_TYPE_WALL, x: 8, y: 4 },
    { type: PLACEMENT_TYPE_WALL, x: 8, y: 3 },
    { type: PLACEMENT_TYPE_WALL, x: 8, y: 1 },
    { type: PLACEMENT_TYPE_WALL, x: 11, y: 4 },
    {
      type: PLACEMENT_TYPE_INFECTED_HERO,
      x: 2,
      y: 4,
      direction: Direction.Right,
    },
    { type: PLACEMENT_TYPE_LOCK, x: 8, y: 10 },
    { type: PLACEMENT_TYPE_LOCK, x: 10, y: 8 },
    { type: PLACEMENT_TYPE_LOCK, x: 6, y: 4 },
    { type: PLACEMENT_TYPE_THIEF, x: 4, y: 6 },
    { type: PLACEMENT_TYPE_THIEF, x: 8, y: 6 },
    { type: PLACEMENT_TYPE_GOAL, x: 6, y: 6 },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 3, y: 2, direction: Direction.Right },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 6, y: 5, direction: Direction.Bottom },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 5, y: 6, direction: Direction.Left },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 7, y: 6, direction: Direction.Right },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 6, y: 7, direction: Direction.Top },
    { type: PLACEMENT_TYPE_WALL, x: 8, y: 5 },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 9, y: 10, direction: Direction.Left },
    { type: PLACEMENT_TYPE_CONVEYOR, x: 10, y: 7, direction: Direction.Bottom },
    { type: PLACEMENT_TYPE_SWITCH_DOOR, x: 2, y: 8 },
    { type: PLACEMENT_TYPE_SWITCH_DOOR, x: 6, y: 8 },
    { type: PLACEMENT_TYPE_SWITCH_DOOR, x: 4, y: 10 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 9 },
    { type: PLACEMENT_TYPE_KEY, x: 10, y: 2 },
    { type: PLACEMENT_TYPE_KEY, x: 2, y: 10 },
    { type: PLACEMENT_TYPE_SWITCH, x: 2, y: 6 },
    { type: PLACEMENT_TYPE_SWITCH, x: 6, y: 10 },
    { type: PLACEMENT_TYPE_FLOUR, x: 10, y: 10 },
    { type: PLACEMENT_TYPE_FLOUR, x: 6, y: 2 },
  ],
};

export default level3;
