import {
  Direction,
  LevelThemes,
  PLACEMENT_TYPE_FIRE,
  PLACEMENT_TYPE_FIRE_PICKUP,
  PLACEMENT_TYPE_FLOUR,
  PLACEMENT_TYPE_FLYING_ENEMY,
  PLACEMENT_TYPE_GOAL,
  PLACEMENT_TYPE_GROUND_ENEMY,
  PLACEMENT_TYPE_HERO,
  PLACEMENT_TYPE_ICE,
  PLACEMENT_TYPE_ICE_PICKUP,
  PLACEMENT_TYPE_INFECTED_HERO,
  PLACEMENT_TYPE_KEY,
  PLACEMENT_TYPE_LOCK,
  PLACEMENT_TYPE_ROAMING_ENEMY,
  PLACEMENT_TYPE_SWITCH,
  PLACEMENT_TYPE_SWITCH_DOOR,
  PLACEMENT_TYPE_TELEPORT,
  PLACEMENT_TYPE_THIEF,
  PLACEMENT_TYPE_WALL,
  PLACEMENT_TYPE_WATER,
  PLACEMENT_TYPE_WATER_PICKUP,
  PLACEMENT_TYPE_CONVEYOR,
} from "~/constants/helpers";

const level2 = {
  theme: LevelThemes.Blue,
  tilesWidth: 9,
  tilesHeight: 9,
  placements: [
    { type: PLACEMENT_TYPE_HERO, x: 2, y: 8 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 1 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 3 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 4 },
    { type: PLACEMENT_TYPE_WALL, x: 3, y: 4 },
    { type: PLACEMENT_TYPE_WALL, x: 1, y: 4 },
    { type: PLACEMENT_TYPE_WALL, x: 1, y: 6 },
    { type: PLACEMENT_TYPE_WALL, x: 3, y: 6 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 6 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 7 },
    { type: PLACEMENT_TYPE_WALL, x: 4, y: 9 },
    { type: PLACEMENT_TYPE_WALL, x: 6, y: 9 },
    { type: PLACEMENT_TYPE_WALL, x: 6, y: 7 },
    { type: PLACEMENT_TYPE_WALL, x: 6, y: 6 },
    { type: PLACEMENT_TYPE_WALL, x: 7, y: 6 },
    { type: PLACEMENT_TYPE_WALL, x: 9, y: 6 },
    { type: PLACEMENT_TYPE_WALL, x: 9, y: 4 },
    { type: PLACEMENT_TYPE_WALL, x: 7, y: 4 },
    { type: PLACEMENT_TYPE_WALL, x: 6, y: 4 },
    { type: PLACEMENT_TYPE_WALL, x: 6, y: 3 },
    { type: PLACEMENT_TYPE_WALL, x: 6, y: 1 },
    { type: PLACEMENT_TYPE_KEY, x: 5, y: 8, color: "GREEN" },
    { type: PLACEMENT_TYPE_KEY, x: 7, y: 5, color: "BLUE" },
    { type: PLACEMENT_TYPE_SWITCH_DOOR, x: 2, y: 4 },
    { type: PLACEMENT_TYPE_SWITCH_DOOR, x: 2, y: 6 },
    { type: PLACEMENT_TYPE_SWITCH_DOOR, x: 8, y: 4 },
    { type: PLACEMENT_TYPE_SWITCH, x: 8, y: 5 },
    { type: PLACEMENT_TYPE_SWITCH_DOOR, x: 6, y: 2 },
    { type: PLACEMENT_TYPE_SWITCH_DOOR, x: 4, y: 2 },
    { type: PLACEMENT_TYPE_INFECTED_HERO, x: 4, y: 2 },

    { type: PLACEMENT_TYPE_LOCK, x: 8, y: 6, color: "GREEN" },
    { type: PLACEMENT_TYPE_LOCK, x: 6, y: 8, color: "BLUE" },
    { type: PLACEMENT_TYPE_FLOUR, x: 8, y: 8 },
    { type: PLACEMENT_TYPE_GOAL, x: 8, y: 2 },
    { type: PLACEMENT_TYPE_THIEF, x: 5, y: 5 },
  ],
};

export default level2;
