import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import configTheme from "~/constants/mantine-theme";

export const metadata: Metadata = {
  title: "Moodify - Feel the breeze on your fingertips",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body>
        <MantineProvider theme={configTheme} withGlobalClasses>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
